<MainScreen>:
    BaseScreenLayout:
        BoxLayout:
            orientation: 'vertical'

            CustomHeader:
                header_text: "Hlavní okno"
                show_back_button: False

            ScrollView:
                MDGridLayout:
                    id: card_grid
                    cols: 1  # výchozí hodnota, přepočítáme později
                    adaptive_height: True
                    padding: 20
                    spacing: 20